- README.md
- added Team members list
- changed look of headers
- fixed a typo
> Team member list Added to README

- create_tables_query.sql
Added additional comments to sql query
> fixed typos in comment

- README.md
- Adding my name to the team members lise
- Adding the issue/branch name formatting to the README.md file
> Modifications to the README.md file

- sql_connector.php
Instructions are found in code comments. Allows us to connect to mysql server using PHP
> Added a PHP to XAMPP SQL connector. 

- home.html
Added website home page layout
features nav-bar and nav-tabs
> Added home.html

- App/SQL_DB/sprint_2_create_tables_query.sql
This is a simplified version of the sql backend to facilitate dev of sprint 2. Please approve.
> Added a simplified sql backend for sprint 2

- App/PHP_HTML/ask_question/ask_question.css
- App/PHP_HTML/ask_question/ask_question.js
- App/PHP_HTML/ask_question/ask_question.php
- App/PHP_HTML/ask_question/db_connection.php
- App/PHP_HTML/ask_question/question_submission.php
Has the css, php, js files that include ask question button, title and description form, and SQL connection with a file to put the details of the question into the SQL table. CSS and JS files are only for the hidden feature.
> #29 User Story 1, Ask Questions Functional (Simple version)

- App/PHP_HTML/answer.php
- App/PHP_HTML/header.php
- App/PHP_HTML/home.php
- App/PHP_HTML/login sample/signIn.html
- App/PHP_HTML/login sample/signUp.html
Replaced the code in both answer.php and home.php to have the include 'header.php' instead. Other codes will be changed when needed. 
Also just some simple grammar changes.
> #58 Header File and inclusion in files.

- App/PHP_HTML/ask_question.js
- App/PHP_HTML/ask_question.php
- App/PHP_HTML/header.php
- App/PHP_HTML/home.php
- App/PHP_HTML/question_submission.php
Added the ask question button to home page. 
Added the new page to check if they are signed in or not.
Gives success message with link back to home back if they are.
Gives error message telling them to log in if they are not.
Added the user_id to given information to the question table.
Miny small changes otherwise(syntax etc)
> #29 Finished User Story 1

- App/SQL_DB/sprint_2_create_tables_query.sql
DROP TABLE IF EXISTS loggedin;
CREATE TABLE loggedin(
user_id INT(32),
logged_in DATETIME DEFAULT CURRENT_TIMESTAMP,
logged_out DATETIME,
active INT(1)
) ENGINE=INNODB;
> #48 #Task 3: Added SQL table for session tracking

- App/PHP_HTML/header.php
Working on search.php file to incorporate keyword search in to the website as per issue #68
> Header.php updated for calling search.php #68

- App/PHP_HTML/search.php
search.php file created for issue #68 .
This allows the user to search for existing questions using keyword matching.
> search.php file created for issue #68

- App/SQL_DB/sprint_3_create_tables_query.sql
Question description column got deleted preventing users to ask new questions. Adding it back.
> #92: fix asked question

- .travis.yml
- config/database.yml
Reverts JoComp27/SOEN341-SA1#114
Files were not used in any way
> Revert "#110 Adding database config files for Travis"

- App/PHP_HTML/login sample/signIn_1.php
- App/PHP_HTML/login sample/signUp.css
- App/PHP_HTML/login sample/signUp.php
For text box fields on sign in and sign up pages
#79
> #116 Ensure the styling holds up on window resizing

- App/PHP_HTML/answer.php
- App/PHP_HTML/deleteAnswer/delete_answer_action.php
- App/PHP_HTML/deleteAnswer/delete_answer_view.php
- App/PHP_HTML/deleteQuestion/delete_question_action.php
> #124 User Can Delete An Answer They Made

- App/PHP_HTML/answer.php
- App/PHP_HTML/modifyAnswer/answerForm.js
- App/PHP_HTML/modifyAnswer/modify_answer_action.php
- App/PHP_HTML/modifyAnswer/modify_answer_view.php
#133
fix for PR #134
Code was removed from revert. Re added it. Its the same code as before, but on latest master.
> #133 User Can Modify An Answer  [ FIX ]

- App/PHP_HTML/answer_state.php
> #148 fixed answer state button view

- App/SQL_DB/sprint_4_create_tables_query.sql
Included spint_4_create_tables_query.sql which contains new tables for user and question subscriptions.
Uncertain about the PRIMARY KEY's for two new tables : user_subscription and question_subscription.
> #139 Added new queries for sprint 4 SQL_DB

- App/SQL_DB/sprint_4_create_tables_query.sql
#152 
I fixed all issues mentioned
> #152 - BUG: Fix Issues with SQL Query File

- App/PHP_HTML/answer.php
- App/PHP_HTML/login sample/profile.php
- App/PHP_HTML/profile.php
-Updated profile.php with newest features (at both locations)
-Fixed issue where all hyperlinks directing to a user profile page always led to the profile page of the user logged in.
> #65 - Fixed issues with User Profile Page

- App/PHP_HTML/answer.php
- App/PHP_HTML/login sample/profile.php
- App/PHP_HTML/profile.php
Reverts JoComp27/SOEN341-SA1#155
Reason:
- Answer no longer displayed beyond 1
- Like/dislike button no longer available.
Will temporarily revert back to stabler built.
> Revert "#65 - Fixed issues with User Profile Page"

- App/PHP_HTML/header.php
- App/PHP_HTML/settings.php
Change to basic information
Cannot change username
Can change email, password, answers 1,2, and 3
Havent gotten to the notifications nor "hidden" attribute?
Must work on profile but error?
> #140 Settings Page

- App/PHP_HTML/answer.php
- App/PHP_HTML/login sample/check_login.php
- App/PHP_HTML/profile.css
- App/PHP_HTML/profile.php
- App/PHP_HTML/question_submission.php
- App/SQL_DB/sprint_4_create_tables_query.sql
#165 
Here are some other changes I made as well:
- general formatting changes and code reduction
- fixed issues with icons
- incrementation on answer and question count works and displays correctly
> #165 BUG - Profile page does not display certain user information

- App/PHP_HTML/answer.php
- App/PHP_HTML/profile.php
Only profile page available was the one of user logged in... now that the issue is fixed users can now view another user's profile page by clicking on their username (hyperlink) in a question or an answer
> #65 - Fix Issues with Profile Pages

- App/PHP_HTML/question_form_view.php
- App/PHP_HTML/question_submission.php
- Tags are now associated to the correct ID
- Removed Associated text for modification
> #145 - Fixing tags association

- App/PHP_HTML/answer.php
- Answer.php now shows the complete answers information
- Removed a stray 9 in the page
> #145 - Fixed error in which answers are not all shown

- App/Tests/QuestionTest.php
- App/Tests/SignInTest.php
- App/Tests/SignupTest.php
add test coverage for sign in, with all branch statements covered
> #188 Add test coverage for sign in

- App/PHP_HTML/login sample/sign_in_submission.php
- App/PHP_HTML/profile.css
- App/PHP_HTML/profile.php
-Updated profile page tab
-Add activity progress bar
-Display all of user's questions
-Fix issue with link to old defective profile page
> #182 Profile page last features update

- AWS/www/html/header.php
- AWS/www/html/profile.css
- AWS/www/html/profile.php
- AWS/www/html/search.php
- AWS/www/html/signUp.css
- AWS/www/html/sign_in_normal.php
- AWS/www/html/sign_in_submission.php
- AWS/www/html/sign_out_submission.php
- AWS/www/html/sign_up.php
- AWS/www/html/style.css
- Removed unused nav options
- Fix search bar
- Integrated latest changes from sprint 4 and beyond
> #188 Final AWS built

- App/PHP_HTML/answer_state_action.php
- App/Tests/AcceptRefuseTest.php
> #188 Refuse accept test
